theme: jekyll-theme-chirpy
baseurl: ''


# mostly stolen from https://github.com/clearbluejar/clearbluejar.github.io/blob/main/_config.yml


lang: en

prefer_datetime_locale:

timezone:
title: oddrune
tagline: random musings

description: >-                        # used by seo meta and the atom feed
  blog, code, and thoughts


# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://oddrune.github.io'


github:
  username: oddrune

twitter:
  username: oddrune

social:
  name: oddrune

  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/oddrune
    - https://github.com/oddrune


theme_mode:   # [light|dark]

paginate: 10


kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

jekyll_compose:
  default_front_matter:
    posts:
      description:
      image:
      category: [TOP_CATEGORIE, SUB_CATEGORIE]
      tags: blog
      mermaid: true
      
